#!/bin/env bash

# Shell script to organize files into seperate directories accoding to their 
# file's extensions

EXTENSIONS=$(find  -- *.*  -maxdepth 0 -not -path '.*'  -type f | \
              awk -F'.' '{print $NF}' | uniq -d) 

for ENDING in $EXTENSIONS
do

  if [[ ! -d "$ENDING" ]] 
  then
    mkdir "$ENDING"
  fi

  mv -- *."$ENDING" "$ENDING"

done
